.PHONY: clean All

All:
	@echo "==========Building project:[ CppStudyProj2 - Debug ]=========="
	@cd "CppStudyProj2" && "$(MAKE)" -f  "CppStudyProj2.mk"
clean:
	@echo "==========Cleaning project:[ CppStudyProj2 - Debug ]----------"
	@cd "CppStudyProj2" && "$(MAKE)" -f  "CppStudyProj2.mk" clean
